# Redpanda Connect Pipeline
# Bridges order events from Kafka to AWS SQS
#
# Flow: Producer → Kafka → Redpanda Connect → SQS → Consumer

input:
  kafka_franz:
    seed_brokers:
      - redpanda:9092
    topics:
      - orders.created
    consumer_group: redpanda-connect-sqs-bridge
    start_from_oldest: true

output:
  aws_sqs:
    url: http://localstack:4566/000000000000/order-events
    region: us-east-1
    endpoint: http://localstack:4566
    credentials:
      id: test
      secret: test
    max_in_flight: 64
    batching:
      count: 10
      period: 1s

logger:
  level: INFO
  format: json
